### ISSUE TITLE
热点互备问题和boomfilter问题

### ISSUE THREAD

**Issue by Euraxluo** [imlgw/gacache#1]
1. 热点互备要达到的目的是为了将该节点没有的,但是其他节点有的数据,缓存在本节点,减少http请求次数;那么直接在远程获取缓存那里用hotCache缓存一下不行么.为什么需要计算QPS呢.直接缓存的话,这个节点没有的数据,也是第一次请求时就拿到了.我感觉应该能直接缓存吧,如果说害怕占内存的话,用一个小小的hostCache应该能行的吧
我这样考虑是因为这个缓存是永不过期的,不知道对不对,求交流,求解答
2. boomfilter的问题
你说是因为在业务端实现比较好,同时每个节点都存一下没有必要.我想了一下,不知道能不能这样做.在ServeHTTP那里加boomfilter,因为这个缓存其实是有入口的,那就是ServeHTTP这个APIServer

**Comment by Reso1mi** [comment]
@Euraxluo 
1. 直接存也可以，原项目是搞了个随机的，1/10的概率会存到本地，我这里算QPS主要是为了保证缓存在本地的数据一定是访问比较频繁的数据（但是实际上hotCache是个lru，一定程度上也能保证缓存的是热点，所以我这里可能有点画蛇添足了，我看见原项目注释上说到了这个，我就随手实现了下，实现的也很简陋）
2. 这里好像确实可以，直接加在ApiServer这个服务上，但是会不会有可能有多个入口呢？感觉还是在业务层好处理一点
> 感谢大佬提issue，这个项目是之前照着网上教程自己练手的项目，然后自己补充了一点点，所以有些地方可能不太对，见谅.

**Comment by Euraxluo** [comment]
今天下午实践了一下
1. 经过实践，发现qps那里确实不好处理（ps:我只看了你的实现）因为keyStatusMap可没有容量限制,没有存到hotCache的key是不断增长的（因为QPS小的应该占大多数）  
groupCache的实现我今天去看了，依然是随机。然后今天测试了一下1/10的几率的实现的效果，大概在重复请求15次左右就加到hotCache中了  

2.  bloomfilter 加在缓存层确实不行  
bloomfilter预热这个工作只有在业务层做比较合适  
>ps:研究了好久，都无法在缓存层解决缓存穿透，只有在业务层做拦截。。

>没有，你才是大佬，我下个项目学习你的那个分布式调度系统。
我是Golang初学者。
